apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  labels:
    kommander.d2iq.io/gitapps-gitrepository-type: catalog
    kommander.d2iq.io/gitrepository-type: catalog
  name: bigbang-catalog
spec:
  interval: 30s
  ref:
    branch: main
  timeout: 30s
  url: https://github.com/d2iq-ps/d2iq-ps-kommander-catalog.git
